[package]
name = "lightdb"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
byteorder = "1" 
positioned-io-preview = "0.3"
lazy_static = "1.4.0"