[package]
edition = "2021"
name = "risinglight"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
simd = ["core_simd"]

[dependencies]
async-stream = "0.3"
async-trait = "0.1"
bitvec = {version = "0.22", features = ["serde"]}
bytes = "1"
core_simd = {git = "https://github.com/rust-lang/portable-simd", rev = "c2f59483f96cf1ab1e92cf10e0f9094432a8374c", optional = true}
csv = "1.1"
enum_dispatch = "0.3"
env_logger = "0.9"
futures = {version = "0.3", default-features = false, features = ["alloc"]}
itertools = "0.10"
jemallocator = "0.3"
log = "0.4"
moka = {version = "0.6", features = ["future"]}
num-traits = "0.2"
parking_lot = "0.11"
prettytable-rs = {version = "0.8", default-features = false}
prost = "0.9"
prost-types = "0.9"
risinglight_proto = {path = "proto"}
rustyline = "9"
serde = {version = "1.0", features = ["derive"]}
serde_json = "1.0"
smallvec = {version = "1.6.1", features = ["serde"]}
sqlparser = {version = "0.10", features = ["serde"]}
thiserror = "1.0"
tokio = {version = "1", features = ["full"]}

[dev-dependencies]
criterion = {version = "0.3", features = ["async_tokio"]}
tempfile = "3"
test-case = "1.2"

[[bench]]
harness = false
name = "e2e"

[[bench]]
harness = false
name = "array"

[profile.bench]
codegen-units = 1
lto = 'thin'

[workspace]
members = [
  "proto",
]
