[package]
edition = "2021"
name = "risinglight"
version = "0.1.0"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["jemalloc"]
simd = []
jemalloc = ["tikv-jemallocator"]

[dependencies]
anyhow = "1"
async-channel = "1"
async-recursion = "1"
async-stream = "0.3"
async-trait = "0.1"
binary-heap-plus = "0.4.1"
bit-set = "0.5"
bitvec = { version = "1", features = ["serde"] }
btreemultimap = "0.1"
bytes = "1"
chrono = "0.4"
clap = { version = "3", features = ["derive"] }
comfy-table = { version = "5.0", default-features = false }
crc32fast = "1"
csv = "1"
dirs = "4"
downcast-rs = "1"
enum_dispatch = "0.3"
erased-serde = "0.3"
futures = { version = "0.3", default-features = false, features = ["alloc"] }
futures-async-stream = { git = "https://github.com/taiki-e/futures-async-stream", rev = "944f407" }
humantime = "2.1.0"
indicatif = { version = "0.16" }
indoc = "1"
iter-chunks = "0.1"
itertools = "0.10"
manifest-dir-macros = "0.1.11"
moka = { version = "0.7", features = ["future"] }
num-traits = "0.2"
parking_lot = "0.12"
paste = "1"
prost = "0.9"
risinglight_proto = { path = "proto" }
rust_decimal = "1"
rustyline = "9"
serde = { version = "1", features = ["derive", "rc"] }
serde_json = "1"
smallvec = { version = "1", features = ["serde"] }
sqllogictest = { git = "https://github.com/risinglightdb/sqllogictest-rs", rev = "21357d4" }
sqlparser = { git = "https://github.com/risinglightdb/sqlparser-rs", rev = "edead1b", features = ["serde"] }
thiserror = "1"
tikv-jemallocator = { version = "0.4", optional = true }
tokio = { version = "1", features = ["full"] }
tokio-util = "0.7"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter", "parking_lot"] }
minitrace = "0.4.0"

[dev-dependencies]
criterion = { version = "0.3", features = ["async_tokio"] }
env_logger = "0.9"
tempfile = "3"
test-case = "1"

[build-dependencies]
glob = "0.3"

[[bench]]
harness = false
name = "e2e"

[[bench]]
harness = false
name = "array"

[profile.bench]
codegen-units = 1
lto = 'thin'

[workspace]
members = [
  "proto",
]
