name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always
  CACHE_KEY_SUFFIX: v20220118

jobs:
  fmt:
    runs-on: ubuntu-latest
    env:
      PROTOC_NO_VENDOR: 1
    steps:
      - uses: actions/checkout@v2
      - run: apt install -y protobuf-compiler
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          components: rustfmt, clippy
      - name: Check code format
        run: cargo fmt --all -- --check
      - name: Clippy
        run: cargo clippy --workspace --all-targets --all-features --locked -- -D warnings

  test:
    runs-on: ubuntu-latest
    env:
      PROTOC_NO_VENDOR: 1
    steps:
      - uses: actions/checkout@v2
      - run: apt install -y protobuf-compiler
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
      - name: Download nextest
        run: curl -fsSL https://get.nexte.st/latest/linux | tar zxf - -C ${CARGO_HOME:-~/.cargo}/bin
      - name: Test
        run: cargo nextest run --workspace --no-fail-fast --all-features --locked
      - name: Doctest
        run: cargo test --doc --workspace --no-fail-fast --all-features --locked

  tpch-test:
    runs-on: ubuntu-latest
    env:
      PROTOC_NO_VENDOR: 1
    steps:
      - uses: actions/checkout@v2
      - run: apt install -y protobuf-compiler
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
      - name: Run TPC-H test
        run: |
          rm -rf risinglight.secondary.db
          make tpch
          cargo build --release
          sudo ./target/release/risinglight -f tests/sql/tpch/create.sql
          sudo ./target/release/risinglight -f tests/sql/tpch/import.sql
          sudo ./target/release/risinglight -f tests/sql/tpch-full/_tpch_full.slt
